UPDATE Defines
	SET Value=5 
	WHERE Name='MAXIMUM_WORK_PLOT_DISTANCE'
	AND EXISTS (SELECT Value FROM Defines WHERE Name='MAXIMUM_WORK_PLOT_DISTANCE');
	SET Value=5 
	WHERE Name='MAXIMUM_BUY_PLOT_DISTANCE'
	AND EXISTS (SELECT Value FROM Defines WHERE Name='MAXIMUM_BUY_PLOT_DISTANCE');